require('./BasicWindow')
require('./drawing-canvas/canvas')
const DesktopMenu = require('./DesktopMenu')
const Desktop = require('./Desktop')
require('./memory/memory-board')
require('./chat/chat-element')
let desktop = new Desktop()
let menu = new DesktopMenu()
desktop.init()
menu.init()
